title: WTD Projects
description: Practical projects to help with people's learning
theme: just-the-docs

url: https://github.com/whiletrue-do/WTD-Projects

aux_links:
  WTD Learning Github: https://github.com/whiletrue-do/WTD-Projects

logo: "/assets/img/logo.png"

favicon_ico: "/assets/img/favicon.ico"